### ISSUE TITLE
Install Required Python Libraries for Sensor Integration

### ISSUE THREAD

**Issue by WTANKW** [mebakid74/Raspberry-Pi-Home-Security-System-M7012E#3]
Setup the ZeroKey api

**Comment by mebakid74** [comment]
Identify and install necessary Python libraries for interfacing with the key sensor module on the Raspberry Pi Zero.

**Comment by mebakid74** [comment]
OpenCV and some libraries are installed.

**Comment by mebakid74** [comment]
All necessary libraries and packages are installed for the base code. Picamera module need a fix!?
